# 端口
server:
  port: 7083
  
spring:
  redis:
      #集群
      cluster:
        nodes: "quanbu-dev-21-12:7000,quanbu-dev-21-13:7000,quanbu-dev-21-14:7000,quanbu-dev-21-12:7001,quanbu-dev-21-13:7001,quanbu-dev-21-14:7001"
      password: edQMJ5mcjp8ai3pfDthFH5LpSakHcf
      timeout: 300000
      pool:
         max-total: 100
         max-active: 30
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: -1
         # 连接池中的最大空闲连接
         max-idle: 8
         # 连接池中的最小空闲连接  
         min-idle: 0
         #向调用者输出“链接”对象时，是否检测它的空闲超时；  
         testWhileIdle: true
         # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.  
         numTestsPerEvictionRun: 50
         #当调用borrow Object方法时，是否进行有效性检查   
         testOnBorrow: true
         #连接的最小空闲时间 默认1800000毫秒(30分钟)
         minEvictableIdleTimeMillis: 30000
         timeBetweenEvictionRunsMillis: 30000
  redis2:
      host: quanbu-dev-21-3
      port: 6379
      database: 1
      password: edQMJ5mcjp8ai3pfDthFH5LpSakHcf
      timeout: 300000
      pool:
         max-total: 100
         max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-idle: 10  # 连接池中的最大空闲连接
         min-idle: 0  # 连接池中的最小空闲连接 
         timeBetweenEvictionRunsMillis: 30000
         #向调用者输出“链接”对象时，是否检测它的空闲超时；  
         testWhileIdle: true  
         # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.  
         numTestsPerEvictionRun: 50  
         #当调用borrow Object方法时，是否进行有效性检查   
         testOnBorrow: true
  redis3:
    cluster:
      nodes: "quanbu-dev-21-12:7000,quanbu-dev-21-13:7000,quanbu-dev-21-14:7000,quanbu-dev-21-12:7001,quanbu-dev-21-13:7001,quanbu-dev-21-14:7001"
    password: edQMJ5mcjp8ai3pfDthFH5LpSakHcf
    timeout: 300000
    pool:
      max-total: 100
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接
      timeBetweenEvictionRunsMillis: 30000
      #向调用者输出“链接”对象时，是否检测它的空闲超时；
      testWhileIdle: true
      # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.
      numTestsPerEvictionRun: 50
      #当调用borrow Object方法时，是否进行有效性检查
      testOnBorrow: true
  redis4:
    host: quanbu-dev-21-3
    port: 6379
    database: 1
    password: edQMJ5mcjp8ai3pfDthFH5LpSakHcf
    timeout: 300000
    pool:
      max-total: 100
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接
      timeBetweenEvictionRunsMillis: 30000
      #向调用者输出“链接”对象时，是否检测它的空闲超时；
      testWhileIdle: true
      # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.
      numTestsPerEvictionRun: 50
      #当调用borrow Object方法时，是否进行有效性检查
      testOnBorrow: true

log:
  project:
    level: debug