spring:
  redis:
      #集群
      cluster:
        nodes: "172.16.4.6:7000,172.16.4.11:7000,172.16.4.9:7000,172.16.4.7:7000,172.16.4.10:7000,172.16.4.8:7000"
      password: ZIRpOslWgskD6EeWNzcPYnMZO49rqA
      #集群--结束
      #单机
      #host: quanbu-dev-data-24
      #port: 6379
      #database: 5
      #password: sIJ9HJG07PJnv17Vl1MSXRKKM4qsuM
      #单机--结束
      timeout: 300000
      pool:
         max-total: 100
         max-active: 30
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: -1
         # 连接池中的最大空闲连接
         max-idle: 8
         # 连接池中的最小空闲连接  
         min-idle: 0
         #向调用者输出“链接”对象时，是否检测它的空闲超时；  
         testWhileIdle: true
         # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.  
         numTestsPerEvictionRun: 50
         #当调用borrow Object方法时，是否进行有效性检查   
         testOnBorrow: true
         #连接的最小空闲时间 默认1800000毫秒(30分钟)
         minEvictableIdleTimeMillis: 30000
         timeBetweenEvictionRunsMillis: 30000
  redis2:
      host: redis-master-env
      port: 32369
      database: 1
      password: FXExwEBo4yqhb20Yb4NDJZ1RdeKyYx
      timeout: 300000
      pool:
         max-total: 100
         max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-idle: 10  # 连接池中的最大空闲连接
         min-idle: 0  # 连接池中的最小空闲连接 
         timeBetweenEvictionRunsMillis: 30000
         #向调用者输出“链接”对象时，是否检测它的空闲超时；  
         testWhileIdle: true  
         # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.  
         numTestsPerEvictionRun: 50  
         #当调用borrow Object方法时，是否进行有效性检查   
         testOnBorrow: true
  redis3:
      cluster:
         nodes: "172.16.4.6:7000,172.16.4.11:7000,172.16.4.9:7000,172.16.4.7:7000,172.16.4.10:7000,172.16.4.8:7000"
      password: ZIRpOslWgskD6EeWNzcPYnMZO49rqA 
      timeout: 300000
      pool:
         max-total: 100
         max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-idle: 10  # 连接池中的最大空闲连接
         min-idle: 0  # 连接池中的最小空闲连接 
         timeBetweenEvictionRunsMillis: 30000
         #向调用者输出“链接”对象时，是否检测它的空闲超时；  
         testWhileIdle: true  
         # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.  
         numTestsPerEvictionRun: 50  
         #当调用borrow Object方法时，是否进行有效性检查   
         testOnBorrow: true
  redis4:
    host: r-bp149m8z8z52jy2dos.redis.rds.aliyuncs.com
    port: 6379
    database: 0
    password: jam1sZiIoHQNmUKFA9VyhaQEuM6zOv
    timeout: 300000
    pool:
      max-total: 100
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接
      timeBetweenEvictionRunsMillis: 30000
      #向调用者输出“链接”对象时，是否检测它的空闲超时；
      testWhileIdle: true
      # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.
      numTestsPerEvictionRun: 50
      #当调用borrow Object方法时，是否进行有效性检查
      testOnBorrow: true
